<a href="https://colab.research.google.com/github/Mhtag/tensorflow/blob/main/00_tensor_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0




```
# This is formatted as code
```

# Create tensor with tf.constant()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimension of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix

matrix = tf.constant([[7,14],
                      [14,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 14],
       [14,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[14.,7.],
                              [7.,14.],
                              [7.,14.]], dtype = tf.float16) # specify the datatype with float16

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[14.,  7.],
       [ 7., 14.],
       [ 7., 14.]], dtype=float16)>

In [ ]:
# Dimension of our another matrix
another_matrix.ndim

2

In [ ]:
# lets create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9,],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# dimension of the tensor

tensor.ndim

3

### Creating tensor with tf.variable

In [ ]:
# create the same tensor with tf.variable as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets try change in one of the element in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# how about we try assign
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# lets try change our unchangeable tensor
unchangeable_tensor[0].assign(7)

### Creating Random tensors

Random tensors are the tensors of some arbitary size which contains random numbers.

In [ ]:
# create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(14) # seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(14)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

### Shuffle the order of elements in A Tensor

In [ ]:
## shuffle a tensor (valuable for data when you want to shuffle your data so when order of data doesnt affect your learming)

not_shuffled = tf.constant([[14,7],
                            [3,4],
                            [1,9]])
not_shuffled

In [ ]:
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42)    # global level random seed
tf.random.shuffle(not_shuffled, seed=42)  # operation level operation seed

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds.
>  **If we want tensor to be in the same order we need to use both the operation level seed and global level random seed**.

In [ ]:
not_shuffled_1 = tf.constant([[14,6],
                              [8,5],
                              [2,3]])

not_shuffled_1

In [ ]:
tf.random.set_seed(21)                       
tf.random.shuffle(not_shuffled_1, seed=42)

### other ways to make tensors

In [ ]:
tf.ones([3,4])

In [ ]:
# create a tensor of all zeroes

tf.zeros([4,3])

In [ ]:
# yoy can also turn Numpy array into tensors

import numpy as np
arr = np.arange(1,25, dtype=np.int32)  # Create a numpy array between 1 and 25
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a = tf.constant(arr, shape=(2,3,4))
b = tf.constant(arr, shape=(2,2,6))
a, b

## Indexing the tensors

In [ ]:
rank_2_tensor = tf.constant([[14,7],
                             [7,14]])
rank_2_tensor

In [ ]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)   # -1 means expand the final axis


### Manipulating tensors (tensor operations)

**Basic operations**



In [ ]:
tensor = tf.constant([[14,7],
                      [7,14]])
tensor + 10

In [ ]:
tensor * 10

In [ ]:
tensor - 10

In [ ]:
# we can use tensor built in function

tf.multiply(tensor, 10)

## Matrix Multiplication

In [ ]:
tf.matmul(tensor, tensor)

**Dot Product**

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X, Y


In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
# Perform matrix multiplication between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

In [ ]:
# perform matix multiplication between X and Y ( reshaped)

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

In [ ]:
# Check the value of Y, reshaped Y , transposed Y

print('normal Y \n', Y)
print()
print('transpose y \n', tf.transpose(Y))
print()
print('reshaped Y \n', tf.reshape(Y, shape=(2,3)))

### Changing the datatype of tensor

In [ ]:
a = tf.constant([1.2,2.6])
a.dtype

In [ ]:
# change for float32 to float16
a = tf.cast(a, dtype=tf.float16)
a.dtype

### Aggregrating Tensors

condensing them from mutiple values down to a smaller amount of values

In [ ]:
# get the absolute values

D = tf.constant([-2,-3])

D, tf.abs(D)

lets go through the following forms of aggregration
* Get the minimum
* Get the maximum
* Get the mean
* Get the sum

In [ ]:
# create a random tensor

E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([26,  8, 79, 16, 89, 31, 42, 50, 53, 59, 50,  9, 30, 13, 22, 72, 82,
       78, 97, 94, 63, 11, 44, 76, 93,  5, 80, 86, 38, 70, 49, 50, 81, 54,
       92, 87, 23, 69, 10, 94, 71, 82,  4, 90, 55, 14, 88, 97, 51, 92])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [ ]:
# Find the Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2819>

In [ ]:
# find the Standard Deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=29.893738474804383>

In [ ]:
# Find the Variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=893.6356>

### Find the positional maximum And minimum

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

### Squeezing the tensor

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=(1,1,1,1,50)))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## One-hot encoding tensors

In [ ]:
some_list = [0,1,2,3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, log, square root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# squareroot
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [ ]:
# the default datatype of each are slightly different

numpy_I = tf.constant(np.array([3.,4.,5.]))
tensor_I = tf.constant([3.,4.,5.])

numpy_I.dtype, tensor_I.dtype

(tf.float64, tf.float32)